### ISSUE TITLE
Doesn't work in 2022.3.20f1

### ISSUE THREAD

**Issue by Minoqi** [JDSherbert/Unity-Serializable-Dictionary#1]
Hello! This is a super cool tool however doesn't seem to work, at least in this version of unity. I believe the issue is with the key and value not appearing right next to each other, but instead as separate lists. So when you go to add a key it won't let you since the values don't match.

`[SerializeField] private SerializableDictionary<string, SpriteAnimationSO> animationsTest = new();`

![image](https://github.com/JDSherbert/Unity-Serializable-Dictionary/assets/25846972/b7a1b43f-164b-4ae3-ad56-e7792fc632ad)

**Comment by JDSherbert** [comment]
Noted! I'll take a look into this 🍡
