### ISSUE TITLE
Inspector not showing the UI as expected

### ISSUE THREAD

**Issue by YuudachiXMMY** [JDSherbert/Unity-Serializable-Dictionary#3]
Hi! Thanks for the effort of visualizing the Serializable Dictionary for Unity.

While I'm using the SerializableDictionary, it doesn't show up as the screenshoot in the README. My serializable dictionary looks like this in Unity inspect, which is the same to what I had previously.
![image](https://github.com/JDSherbert/Unity-Serializable-Dictionary/assets/41570678/69b2c03b-0f94-4523-a4b6-4b2c71f75033)

`[SerializeField] private SerializableDictionary<string, int> attackType;`

Unity version: 2022.3.28f1

**Comment by JDSherbert** [comment]
Hi @YuudachiXMMY! 
The screenshot was taken while using Odin Inspector for Unity which may explain the differences.
In both instances it should still function as a serializable dictionary.

You can grab odin from here: 
- Github: https://github.com/TeamSirenix/odin-serializer
- Unity Asset Store: https://assetstore.unity.com/packages/tools/utilities/odin-inspector-and-serializer-89041

**Comment by JDSherbert** [comment]
I'm 99% sure this is the script that serializes it in the way in the screenshot:
https://github.com/TeamSirenix/odin-serializer/blob/master/OdinSerializer/Core/Formatters/DictionaryFormatter.cs

**Comment by YuudachiXMMY** [comment]
Thank for all those efforts:)

Yes, the script serializes as expected, I was just trying to use the inspector function as well and did find that the Odin inspector provides the expected function.

Thanks you so much!

**Comment by JDSherbert** [comment]
Perfect! I'll add that to the Readme.md in case anyone else runs into the same issue!
